### ISSUE TITLE
Unresolved directive in <stdin>

### ISSUE THREAD

**Issue by jo2** [spring-guides/gs-accessing-data-rest#29]
In the getting started guide the code examples can't be found (see image).

![image](https://user-images.githubusercontent.com/7516893/65017536-55538680-d927-11e9-9ad5-47fb997b517c.png)

**Comment by dsyer** [comment]
Cache was stale. Try now.

**Comment by avivmu** [comment]
It still occurs:
![image](https://user-images.githubusercontent.com/19804341/103643010-a7754c80-4f5c-11eb-81f8-157c512b3b49.png)

**Comment by dsyer** [comment]
Works for me now (cleared the cache again). Make sure you refresh the browser cache as well.

**Comment by avivmu** [comment]
not it works. When you say 

> cleared the cache

Which cache do you mean? Seems that you have control of this cache while I don't.
Also looks like the problem will recur again in the future

**Comment by dsyer** [comment]
It is cached on the server, and yes, the operators have access and users do not. It happens all the time unfortunately, not specifically for this guide. It's probably a race condition with github webhooks and there isn't much we can do except wait for people to notice.

**Comment by avivmu** [comment]
Why not clear the cache depending on some event that will probably make it stale? I'm not familiar with this cache so maybe my question is not relevant

**Comment by dsyer** [comment]
We do that already. It's just that it's a distributed system and it's on the internet (github webhooks), so there are race conditions. Most of the time it works fine.

**Comment by gregturn** [comment]
@dsyer is correct. Every time an update is pushed to github, we fire a webhook signaling spring.io to wipe the cache for that guide. Then someone else requests the same guide BEFORE github has actually updated the source code based on the original push.

It's irritating, but a lot easier to manage than regenerating the guide every single time someone wants to read it.

**Comment by avivmu** [comment]
So the order of events is:
1. An update is pushed to github which triggers:
2. The (read-only) cache being wiped, then, _and before 5_
3. A user asks for the guide, which causes:
4. The _empty_ cache to fetch the _old_ source code
5. New source code is updated on the server, but:
6. From now on and till the next wipe, the cache references the old guide and the newly source code is never fetched

Is this correct? If so, then why not insert another wipe, after step 5

**Comment by gregturn** [comment]
That is what github's processing appears to do. The trick is, we only control (2). (1) and (5) are governed by github's internal processes. We could be talking a 200 ms window between the two, but being popular increases the odds of someone occasionally hitting it.

Speaking out loud...we COULD have (2) actually implement something like a 5-second delay before it wipes the cache. What about that @bclozel?

**Comment by avivmu** [comment]
> (1) and (5) are governed by github's internal processes

We are talking about travis, aren't we? If so there is support for post script actions or post success actions:
From [Travis job lifecycle](https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle):

> Travis CI can run custom commands in the phases:
before_install - before the install phase
before_script - before the script phase
after_script - after the script phase.
after_success - when the build succeeds (e.g. building documentation), the result is in TRAVIS_TEST_RESULT environment variable

**Comment by dsyer** [comment]
We weren't talking about travis, but I guess it could play a role. It's just another webhook to fire out of order though, so I'm not sure it would help. I'm not sure the order of events above is correct either - when it goes wrong it's not because it's showing old content, it's because the cache was refreshed at a time that the content was (apparently, but inexplicably) unavailable. If we can be confident we understand the race condition there's a (small) chance we can fix it, or at least make it less likely. I don't think we got there yet, but thanks for all the ideas and analysis.

**Comment by gregturn** [comment]
This is purely github's flow. We don't depend upon travis to apply changes.

**Comment by avivmu** [comment]
Can you log when the cache fetches this data and what data was fetched?

**Comment by bclozel** [comment]
I don't understand how this problem is related to a caching problem or some racing issue.

The error message seems to indicate that asciidoctor didn't render the content of included files. To render a guide, the application is downloading the repository as a tarball, unzipping it and calling the asciidoctor engine on the main file. The rendered version could be inconsistent if the the tarball didn't reflect the latest changes. Looking at recent commits, it doesn't seem those files were modifed/moved recently, so I don't understand how this error could be solved with delays or lifecycle improvements.

I don't understand yet the cause of this problem. Is the file not present on the file system when the rendering happens? Is there a concurrency bug in the rendering application?
